export default{
    user1: {
        name: "حسینی",
        email: "h@gmail.com",
        phone: "33223322",
        mobile: "091256256",
        cType: "شرکت",
        utype: "حقیقی",
        packName: "بسته اول",
        cost: "۳۰۰۰۰",
        state: false,
        thingName: "شی اول",
        thingType: "تایپ ۱",
        projectName: "پروژه اول",
        projectState: false,
        _date: "1994-11-05",
        status: false,
    },
    user2: {
        name: "حسنی ",
        email: "hasani@gmail.com",
        phone: "33223322",
        mobile: "091256256",
        cType: "نظامی",
        utype: "حقیقی",
        packName: "بسته اول",
        cost: "۳۰۰۰۰",
        state: true,
        thingName: "شی اول",
        thingType: "تایپ ۱",
        projectName: "پروژه اول",
        projectState:  true,
        _date: "1994-11-05",
        status: false,
    },
    user3: {
        name: "سعیدی",
        email: "saeedi@gmail.com",
        phone: "33223322",
        mobile: "091256256",
        cType: "شرکت",
        utype: "حقوقی",
        packName: "بسته اول",
        cost: "۳۰۰۰۰",
        state: false,
        thingName: "شی اول",
        thingType: "تایپ ۱",
        projectName: "پروژه اول",
        projectState: true,
        _date: "1994-11-05",
        status: true,
    },
    user4: {
        name: "قاسمی",
        email: "ghasemi@gmail.com",
        phone: "33223322",
        mobile: "091256256",  
        cType: "نظامی",
        utype: "حقیقی",
        packName: "بسته اول",
        cost: "۳۰۰۰۰",
        state: true,
        thingName: "شی اول",
        thingType: "تایپ ۱",
        projectName: "پروژه اول",
        projectState: false,
        _date: "1994-11-05",
        status: true,
    },
    user5: {
        name: "رنجبر",
        email: "ranjbar@gmail.com",
        phone: "33223322",
        mobile: "091256256", 
        cType: "NGO",
        utype: "حقوقی",
        packName: "بسته اول",
        cost: "۳۰۰۰۰",
        state: true,
        thingName: "شی اول",
        thingType: "تایپ ۱",
        projectName: "پروژه اول",
        projectState: true,
        _date: "1994-11-05",
        status: true,
    },
  
}