const routes = {
  '/': 'خانه',
  '/base': 'Base',
  '/base/cards': 'Cards',
  '/base/forms': 'Forms',
  '/base/switches': 'Switches',
  '/base/tables': 'Tables',
  '/base/tabs': 'Tabs',
  '/base/breadcrumbs': 'Breadcrumbs',
  '/base/carousels': 'Carousels',
  '/base/collapses': 'Collapses',
  '/base/jumbotrons': 'Jumbotrons',
  '/base/list-groups': 'List Groups',
  '/base/navbars': 'Navbars',
  '/base/navs': 'Navs',
  '/base/paginations': 'Paginations',
  '/base/popovers': 'Popovers',
  '/base/progress-bar': 'Progress Bar',
  '/base/tooltips': 'Tooltips',
  '/buttons': 'Buttons',
  '/buttons/buttons': 'Buttons',
  '/buttons/social-buttons': 'Social Buttons',
  '/buttons/button-dropdowns': 'Button Dropdowns',
  '/buttons/button-groups': 'Button Groups',
  '/charts': 'Charts',
  '/dashboard': 'داشبورد',
  '/icons': 'Icons',
  '/icons/flags': 'Flags',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/notifications': 'Notifications',
  '/notifications/alerts': 'Alerts',
  '/notifications/badges': 'Badges',
  '/notifications/modals': 'Modals',
  '/theme': 'Theme',
  '/theme/colors': 'Colors',
  '/theme/typography': 'Typography',
  '/widgets': 'Widgets',
  '/news': 'اخبار',
  '/profile': 'حساب کاربری',

  '/projects': 'لیست پروژه‌ها',
  '/project': 'لیست پروژه‌ها',
  '/projects/view': 'نمایش پروژه',
  '/projects/view/$$': 'نمایش پروژه',
  '/projects/manage': 'مدیریت پروژه',
  '/project/manage/createThing': 'ایجاد شی',
  '/project/manage/createThing/$$': 'ایجاد شی',
  '/projects/manage/$$': 'مدیریت پروژه',

  '/admin/globalCodec': 'مدیریت پروژه',

  '/things': 'لیست اشیا',
  '/things/edit': 'ویرایش شی',
  '/things/edit/$$': 'ویرایش شی',
  '/things/new': 'ایجاد شی',
  '/things/new/$$': 'ایجاد شی',
  '/things/excel': 'آپلود فایل Excel',
  '/things/excel/$$': 'آپلود فایل Excel',

  '/codec':'ارسال کدک',
  '/codec/$$':'ارسال کدک',
  '/scenario':'ارسال سناریو',
  '/scenario/$$':'ارسال سناریو',
  '/template':'ارسال قالب',
  '/template/$$':'ارسال قالب',

  '/gateways': 'لیست گذرگاه ها',
  '/gateways/new': 'افزودن گذرگاه',
  '/gateways/new/$$': 'افزودن گذرگاه',
  '/gateways/view': 'مشاهده گذرگاه',
  '/gateways/view/$$': 'مشاهده گذرگاه',

  '/device-profile/list': 'پروفایل اشیا',
  '/device-profile/new': 'افزودن پروفایل اشیا',
  '/device-profile/new/$$': 'افزودن پروفایل اشیا',
  '/device-profile/list/view': 'مشاهده پروفایل اشیا',
  '/device-profile/list/view/$$': 'مشاهده پروفایل اشیا',

  '/packages':'خرید بسته',
  '/transactions': 'تراکنش های کاربر',
  '/admin/packages/show': 'مدیریت بسته‌ها',
  '/admin/packages': 'مدیریت بسته‌ها',
  '/admin/packages/edit': 'ویرایش بسته',
  '/admin/packages/new': 'افزودن بسته جدید',
  '/admin/packages/edit/$$': 'ویرایش بسته',

  '/admin/users/list':'مدیریت کاربران سیستم',
  '/admin/users/info':'ویرایش کاربر',
  '/admin/users/info/$$':',ویرایش کاربر',
  '/admin/users': 'مدیریت کاربران سیستم',

  '/admin/transactions': 'مدیریت تراکنش‌های سیستم',
  '/admin/roles': 'مدیریت نقش‌ها',
  '/admin/links': 'مدیریت پروژه',
  '/portals': 'مدیریت پرتال پرداخت'
};
export default routes;
