const routes = {
  '/': 'خانه',
  '/base': 'Base',
  '/base/cards': 'Cards',
  '/base/forms': 'Forms',
  '/base/switches': 'Switches',
  '/base/tables': 'Tables',
  '/base/tabs': 'Tabs',
  '/base/breadcrumbs': 'Breadcrumbs',
  '/base/carousels': 'Carousels',
  '/base/collapses': 'Collapses',
  '/base/jumbotrons': 'Jumbotrons',
  '/base/list-groups': 'List Groups',
  '/base/navbars': 'Navbars',
  '/base/navs': 'Navs',
  '/base/paginations': 'Paginations',
  '/base/popovers': 'Popovers',
  '/base/progress-bar': 'Progress Bar',
  '/base/tooltips': 'Tooltips',
  '/buttons': 'Buttons',
  '/buttons/buttons': 'Buttons',
  '/buttons/social-buttons': 'Social Buttons',
  '/buttons/button-dropdowns': 'Button Dropdowns',
  '/buttons/button-groups': 'Button Groups',
  '/charts': 'Charts',
  '/dashboard': 'داشبورد',
  '/icons': 'Icons',
  '/icons/flags': 'Flags',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/notifications': 'Notifications',
  '/notifications/alerts': 'Alerts',
  '/notifications/badges': 'Badges',
  '/notifications/modals': 'Modals',
  '/theme': 'Theme',
  '/theme/colors': 'Colors',
  '/theme/typography': 'Typography',
  '/widgets': 'Widgets',
  '/news': 'اخبار',
  '/profile': 'حساب کاربری',
  '/projects/list': 'لیست پروژه ها',
  '/projects/new': 'ساخت پروژه',
  '/projects/view': 'نمایش پروژه',
  '/projects/manage': 'مدیریت پروژه',
  '/things': 'اشیاء',
  '/things/excel': 'آپلود فایل Excel',
  '/things/list': 'لیست اشیاء',
  '/gateways/list': 'لیست گذرگاه ها',
  '/gateways/new': 'ساخت گذرگاه',
  '/gateways/view': 'نمایش گذرگاه',
  '/device-profile/list': 'پروفایل اشیا',
  '/device-profile/new': 'ساخت پروفایل اشیاء',
  '/users': 'لیست کاربران',
  '/packages': 'بسته ها',
  '/buyedPackages': 'بسته های خریداری شده',
  '/transactions': 'تراکنش ها',
  '/payment-portal/management': 'مدیریت پرتال پرداخت',
  '/Package/Managment': 'مدیریت بسته ها',
};
export default routes;
